language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "books-a-lot-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle

 before_deploy:
   - rm -rf node_modules # omit from the tarball, since we skip cleanup
 deploy:
   skip_cleanup: true # prevents travis from deleting the build
   provider: heroku
   app: books-a-lot-co # see README
   api_key:
     secure: fHfsf8Gh+4CaLGwJnkoUz/MfVRGoCcsRkY4N44ubufbOLFsWSJSi4bpYVDbS5IhBQFKCs3DAJPFmJdXFLKya2aoEaeQVibwsvGV2scL3aeVWR2k0I02XgH+ikzH7Fa3bv9zhLAwbceD6IDmc3/kyWglaSRQbb0l46oOCF398RZmrZcdokVHhx2n0Jov6L0ejguL0lMq9raZHnNWZgYa/nfJVWOh/bHIHXLwFWjT/VI6h51b7/l7A6Yn21uELNz3pHI/D7HQAHt+UTcMNiO0dgTdnu58ujKLP1XZj3jyC0hOr7SRywpQsZytCe+I3R9ZtSJ+gDhncSpU/KPXmyvrc8VbzUhxJHf91ghWfMMnu+f+zVWI//Y9NaZ8WkXU3qGM9Rw4rVbo+Zog4cnt5Wpt/eUOHRm1ZdcXnv/EYqaf5o/TfK2CqWucvfbcZIGWQE+64dE0AO1bD67kM4pHKyY7zmZgdwJhRP2DPTV3Rln23N5NIeO0DDnUEBrZksEeDDZJGIxA9wrwqOXaCj4J7pTwc3iu80Jtr+HhYKWCpFHj3fqWvH3KctN8pzF0H8Jxf5RUZq4egUSTK+qqQbJxzAL4CCR+mzxL3KA3jkn6B38oPD45a+0yUl0W8iLmn/n0SufUkWJiuP1WCY8MemAeXBebsWw4E1n9hlsza+ZuiC2Qfctk=
# ignore me pls
